---
title: "Plots for the Mini Atlas Paper"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

Rename the param as theta to avoid confusion

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F, fig.width = 6, fig.height = 6
)
libs <- c("here", "tidyverse", "DailyHRB", "RColorBrewer")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```

```{r, eval = FALSE}
isPareto <- function(x, df) {
  fraction <-  as.numeric(x[7])
  nb  <- as.numeric(x[10])
  return(
    !any(df$fraction_replicable_cells > fraction &
        df$nb_clusters > nb
    )
  )
}
toRank <- function(i) {
  case_when(
    i == "Initial" ~ 1,
    i == 33 ~ 2,
    i == 66 ~ 3,
    i == 90 ~ 4,
    i == "Final" ~ 5
  )
}

df <- read.table(here("data", "Replicability", "Dune", "smart_tenx",
                      "consensus_cluster_replicability.txt"),
                 stringsAsFactors = FALSE)
df <- df %>% mutate(nb_clusters = replicable_clusters + non_replicable_clusters) %>%
  filter(clustering_name != "Consensus" | level == "Final")
df$isPareto <- apply(as.matrix(df), 1, isPareto, df = df)
df$isPareto <- as.character(df$isPareto)
df$level <- lapply(df$level, toRank) %>% unlist()
df$level <- as.numeric(df$level)
df <- df %>% arrange(level)
ggplot(df, aes(x = nb_clusters / 4,
               y = fraction_replicable_cells)) +
  geom_text(aes(color = isPareto,
                 alpha = isPareto,
                 label = level),
             size = 5) +
  theme_classic() +
  geom_path(aes(group = clustering_name),
            alpha = .1, arrow = arrow(angle = 10,
                                      length = unit(0.15, "in"))) +
  labs(x = "Resolution",
       y = "Replicability",
       col = "Pareto equilibrium\npoint") +
  scale_color_manual(values = c("grey", "red")) +
  scale_alpha_manual(values = c(.5, 1)) +
  geom_text(data = df %>% filter(level == 1 | clustering_name == "Consensus"),
                  aes(label = clustering_name,
                      y = fraction_replicable_cells - .03),
                  alpha = .5, size = 3) +
  guides(alpha = FALSE)
```

# Examples

```{r}
folders <- c(
             "cells",
             "nuclei",
             "tenx_v3",
             # "tenx",
             "smart")
rep <- lapply(folders, function(type) {
  if (type == "smart") {
    df <- read.table(here::here("data", "Replicability", "Dune_Smart", "Normal",
                              "consensus_cluster_replicability.txt"))
  } else {
    df <- read.table(here::here("data", "Replicability", "Dune", type,
                              "consensus_cluster_replicability.txt")) %>%
      # filter(is.na(level)) %>%
      mutate(level = word(clustering_method, 2, sep = "\\."),
             level = as.numeric(level))
  }
  df <- df %>%
    filter(level %in% c(0, 30, 70, 90, 100)) %>%
    mutate(type = type,
           clustering_method = str_remove(clustering_method, "\\..+")) %>%
    select(-level) %>%
    filter(clustering_method != "Consensus")
  return(df)
})

rep <- rep %>% 
  bind_rows() %>%
  mutate(Comparison = case_when(
                                type == "cells" ~ "Smart vs V3 Cells",
                                type == "nuclei" ~ "Smart vs V3 Nuclei",
                                type == "smart" ~ "Between Smart-Seq datasets",
                                type == "tenx_v3" ~ "Between 10x V3 datasets",
                                type == "tenx" ~ "Between 10x V2 datasets",
                                # type == "Lab" ~ "Between Labs"
                                ),
         Group = if_else(str_detect(Comparison, "Between"), "Plateform", "Material"))
plateform <- rep %>% filter(Group == "Plateform")
material <- rep %>% filter(Group == "Material")
p <- ggplot(data = rep,
            mapping = 
            aes(x = (replicable_clusters + non_replicable_clusters) / 2,
                y = replicable_clusters / 
                   (replicable_clusters + non_replicable_clusters))) +
  geom_point(aes(shape = Comparison, col = Group), size = 4, alpha = .8,
             data = plateform) +
  geom_point(aes(col = Group), size = 4, alpha = .8, shape = "plus",
             data = material %>% filter(type == "cells")) +
  geom_point(aes(col = Group), size = 4, alpha = .8, shape = "square",
             data = material %>% filter(type == "nuclei")) +
  labs(x = "Number of clusters (Resolution)", y = "Fraction of replicable clusters",
       title = "Resolution vs. replicability tradeoff\nfor `off-the-shelf` methods.") + 
  # scale_x_continuous(limits = c(17, 70)) +
  scale_y_continuous(limits = c(0, .6), breaks = 0:3 / 5,
                     labels = paste0(0:3 * 20, "%")) +
  scale_color_brewer(palette =  "Set1", 
                     labels = c("for 10X v3 datasets", "for Smart-Seq datasets")) +
  scale_shape_discrete(
    labels = c("for single-cell datasets", "for single-nuclei datasets")) +
  guides(color = guide_legend(title = "Replicability betwen Cell and Nuclei",
                              override.aes = list(
                                col = brewer.pal(3, "Set1")[c(2, 2)],
                                shape = 16:17)
                               ),
         shape = guide_legend(title = "Replicability betwen 10X v3 and Smart-Seq",
                              override.aes = list(
                                col = brewer.pal(3, "Set1")[c(1, 1)],
                                shape = c(3, 15)), order = 1,
                               )) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black", size = rel(1)),
        legend.position = c(.9, .75),
        legend.text = element_text(size = 8),
        legend.box.background = element_rect(color = "black", size = .5),
        legend.margin = margin(-10, 0, 0, 0, "pt"),
        legend.box.margin = margin(15, 5, 5 , 5, "pt"),
        legend.title = element_text(size = 12),
        plot.title = element_text(hjust = .8, size = 15),
        plot.margin = margin(5, 100, 5, 5, "pt")) +
  NULL
p
ggsave(here::here("Figures", "MiniAtlas", "panel_2h.pdf"),
       plot = p, height = 6, width = 6)
```

```{r, eval=FALSE}
p <- ggplot(rep, aes(x = (replicable_clusters + non_replicable_clusters) / 2)) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "black", size = rel(1)),
        legend.background = element_rect(colour = "black")) +
  labs(x = "Resolution",
       title = "Quantifying the trade-off between replicability and resolution") +
  scale_x_continuous(limits = c(10, 100)) +
  geom_point(size = 4, alpha = .8,
               aes(col = Comparison, y = replicable_clusters)) +
  scale_y_continuous(limits = c(0, 40),
                     breaks = 0:4 * 10) +
  theme(legend.position = c(.85, .8)) +
  # scale_x_continuous(limits = c(17, 70)) +
  labs(y = "Number of replicable clusters")
# ggsave(here::here("Figures", "MiniAtlas", "number.pdf"),
#        plot = p2, height = 6, width = 6)
p
```