---
title: "Plots for singleMethod versus ARI merging"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.align = "center", echo = F
)
libs <- c("here", "tidyverse", "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```


```{r laod data}
toRank <- function(i) {
  case_when(
    i == "Initial" ~ 1,
    i == 33 ~ 2,
    i == 66 ~ 3,
    i == 90 ~ 4,
    i == "Final" ~ 5
  )
}

load_Dune <- function(comparison) {
  df <- read.table(here("data", "Replicability", "Dune_Smart", comparison,
                        "consensus_cluster_replicability.txt"))
  df <- df %>% filter(!str_detect(clustering_method, "Consensus")) %>%
    mutate(clustering_name = as.character(clustering_name))
  df$level <- lapply(df$level, toRank) %>% unlist()
  df$level <- as.numeric(df$level)
  df$clustering_name[df$clustering_name == "sc3"] <- "SC3"
  return(df)
}

read_single_method <- function(Method,
                               result_dir = here("data", "Replicability",
                                                 "SingleMethod", "smart")) {
  df <- read.table(file.path(result_dir, "consensus_cluster_replicability.txt"))
  df <- df %>% filter(clustering_name == Method)
}

filter_sc3_param <- function(dune, SC3) {
  sc3_init <- dune %>% filter(clustering_method == "sc3.Initial")
  sc3_param <- SC3 %>% filter(
    fraction_replicable_clusters == sc3_init$fraction_replicable_clusters &
    fraction_replicable_cells == sc3_init$fraction_replicable_cells)
  sc3_param <- sc3_param$level %>% as.character() %>% as.numeric()
  df <- SC3 %>% 
    mutate(level = as.numeric(as.character(level))) %>%
    filter(level <= sc3_param) 
  return(df)
}

filter_monocle_param <- function(dune, Monocle) {
  monocle_init <- dune %>% filter(clustering_method == "Monocle.Initial")
  monocle_param <- Monocle %>% filter(
    fraction_replicable_clusters == monocle_init$fraction_replicable_clusters &
    fraction_replicable_cells == monocle_init$fraction_replicable_cells)
  monocle_param <- monocle_param$level %>% str_remove("^k_") %>% as.numeric()
  df <- Monocle %>% 
    mutate(level = str_remove(level, "^k_") %>% as.numeric()) %>%
    filter(level >= monocle_param) 
  return(df)
}

filter_seurat_param <- function(dune, Seurat) {
  df <- Seurat %>%
    mutate(res = str_remove(level, ",.*$") %>% str_replace("_", "\\.") %>%
             as.numeric(),
           k = str_remove(level, "^.*,") %>% as.numeric())
  seurat_init <- dune %>% filter(clustering_method == "Seurat.Initial")
  seurat_param <- df %>% filter(
    fraction_replicable_clusters == seurat_init$fraction_replicable_clusters &
    fraction_replicable_cells == seurat_init$fraction_replicable_cells)
  df <- df %>% 
    filter(res <= seurat_param$res & k == seurat_param$k)  %>%
    mutate(level = res) %>%
    select(-res, -k)
  return(df)
}

read_all <- function(comparison = "Normal") {
  dune <- load_Dune(comparison = comparison)
  Seurat <- read_single_method(Method = "Seurat") %>%
    filter_seurat_param(dune = dune, Seurat = .)
  SC3 <- read_single_method(Method = "SC3") %>%
    filter_sc3_param(dune = dune, SC3 = .)
  Monocle <- read_single_method(Method = "Monocle") %>%
    filter_monocle_param(dune = dune, Monocle = .)
  single_method <- bind_rows(
    SC3, Monocle, Seurat
  )
  df <- bind_rows(
    Dune = dune,
    single_method = single_method,
    .id = "method"
  )
}

plot_comp <- function(df) {
  linetypes <- c("solid", "dotted")
  names(linetypes) <- c("Dune", "single_method")

  p <- ggplot(df %>% 
           mutate(nb_clusters = replicable_clusters + non_replicable_clusters) %>%
           arrange(level),
         aes(x = nb_clusters / 2,
             y = fraction_replicable_cells,
             col = clustering_name,
             linetype = method,
             group = interaction(clustering_name, method))) +
    geom_path(size = 1.8) +
    my_theme() +
    scale_linetype_manual(values = linetypes) +
    scale_color_brewer(type = "qual") +
    labs(x = "Resolution",
         y = "Replicability",
         col = "Clustering\nmethod",
         linetype = "Method of\nmerging")
  return(p)
}
```

# Single Methods
## Seurat 
### Varying the k parameter

```{r seurat k}
Seurat <- read_single_method(Method = "Seurat") %>% 
  mutate(level = str_extract(clustering_method, ",.*$") %>%
           str_remove(., "^,") %>%
           factor(., levels = c("30", "50", "100")),
         clustering_method = 
           str_extract(clustering_method, "^.*,") %>%
           str_remove(., "Seurat\\.") %>%
           str_remove(., ",$") %>%
           str_replace(., "_", "."))
ggplot(Seurat %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = clustering_method, shape = level)) +
  geom_point() +
  geom_path(aes(group = factor(clustering_method))) +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "resolution",
       shape = "k param", title = "Seurat, varying the k parameter")
p <- ggplot(Seurat, aes( y = (replicable_clusters + non_replicable_clusters) / 2,
                         x = as.numeric(clustering_method), col = level)) +
  geom_line() +
  my_theme() +
  labs(x = "Resolution", y = "Number of clusters", col = "K parameter")
ggsave(filename = here("Figures", "Paper", "Supp-Seurat-param.pdf"), p)
```

### Varying the resolution

```{r seurat resolution}
ggplot(Seurat %>% arrange(clustering_method),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  geom_path(aes(group = factor(level))) +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "k param",
       title = "Seurat, varying the resolution parameter")
```

## SC3

```{r sc3}
SC3 <- read_single_method("SC3") %>%
         mutate(level = as.numeric(as.character(level)))
ggplot(SC3 %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "K",
       title = "SC3, varying the k parameter")
```

## Monocle

```{r Monocle}
Monocle <- read_single_method(Method = "Monocle") %>% 
  mutate(level = str_remove(level, "^k_") %>% as.numeric()) %>%
  filter(level >= 10)
ggplot(Monocle %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "K",
       title = "Monocle, varying the k parameter")
```
  
## All at once

```{r all}
p <- ggplot(bind_rows(SC3 %>% select(-level),
                 Monocle %>% select(-level),
                 Seurat %>% select(-level)),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = clustering_name)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "Clustering Method")
p
ggsave(filename = here("Figures", "Paper", "tradeOff.pdf"), p)
```

# ARI Merging versus singleMerge
We have three scenarios

## Scenario A
```{r}
p <- plot_comp(read_all()) +
  scale_x_continuous(limits = c(10, 30))
ggsave(filename = here("Figures", "Paper", "A-singleMethod.pdf"), p)
plot_comp(read_all())
```

## Scenario B
```{r}
plot_comp(read_all(comparison = "large2"))
```

## Scenario C
```{r}
plot_comp(read_all(comparison = "large3"))
```

## All together

```{r}
df <- bind_rows(A = read_all("Normal"),
                B = read_all("large2"),
                C = read_all("large3"),
                .id = "Run")
df <- df %>% 
  group_by(Run, method, clustering_name) %>%
  dplyr::mutate(
    nb_clusters = replicable_clusters + non_replicable_clusters) %>%
  arrange(desc(nb_clusters)) %>%
  dplyr::mutate(
    nb_clusters = dplyr::first(nb_clusters) - nb_clusters,
         fraction_replicable_cells = fraction_replicable_cells - 
           dplyr::first(fraction_replicable_cells)) %>%
  filter(nb_clusters < 30)
ggplot(df,
       aes(x = nb_clusters / 2,
           y = fraction_replicable_cells,
           group = interaction(clustering_name, Run),
           col = clustering_name,
           label = level)) +
    geom_line(size = 1.8) +
    my_theme() +
    labs(x = "Relative Coarseness",
         y = "Relative Replicability",
         col = "Clustering\nmethod",
         linetype = "Method of\nmerging") +
  facet_wrap(~method) +
    # theme(axis.title = element_text(size = 20),
    #       axis.text = element_text(size = 15),
    #       legend.title = element_text(size = 20),
    #       legend.text = element_text(size = 15))  +
    NULL +
  geom_hline(yintercept = 0, col = "black")
```

# single Method on 10x and Smart-Seq together

```{r}
Monocle <- read_single_method(Method = "Monocle",
      result_dir = here("data", "Replicability", "SingleMethod", "tenx"))
Seurat <- read_single_method(Method = "Seurat",
      result_dir = here("data", "Replicability", "SingleMethod", "tenx"))

ggplot(bind_rows(Monocle, Seurat),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = clustering_name)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Resolution", y = "Replicability", col = "Clustering Method")
```