---
title: "Plots for singleMethod versus ARI merging"
author: "Hector Roux de Bézieux"
date: '`r format(Sys.time(), "%d %B , %Y")`'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r packages, include=F}
library(knitr)
opts_chunk$set(
  fig.pos = "!h", out.extra = "", warning = F, message = F,
  fig.width = 5, fig.align = "center", echo = F
)
libs <- c("here", "tidyverse", "DailyHRB")
suppressMessages(
  suppressWarnings(sapply(libs, require, character.only = TRUE))
)
rm(libs)
```


```{r laod data}
singleMethod <- read.table(here("Replicability", "singleMethod", "smart",
                               "consensus_cluster_replicability.txt")) %>%
  mutate(
    clustering_name = as.character(clustering_name),
    clustering_name = case_when(clustering_name == "seurat" ~ "Seurat",
                                clustering_name == "Rsec" ~ "RSEC",
                                TRUE ~ clustering_name),
    merging_type = "singleMethod")

# Load and clean the results from ARI mergings
toRank <- function(i) {
  case_when(
    i == "Initial" ~ 1,
    i == 33 ~ 2,
    i == 66 ~ 3,
    i == 90 ~ 4,
    i == "Final" ~ 5
  )
}

ARIMerge <- read.table(here("Replicability", "smart",
                               "consensus_cluster_replicability.txt")) %>%
  mutate(
    level = str_extract(clustering_method, "\\..+$"),
    level = str_remove(level, "^\\."),
    level = toRank(level),
    clustering_method = str_remove(clustering_method, "\\..+$"),
    clustering_name = as.character(clustering_name),
    clustering_name = case_when(clustering_name == "sc3" ~ "SC3",
                                TRUE ~ clustering_name),
    merging_type = "ARI") %>%
  filter(clustering_method != "Consensus")
```

# Single Methods
## Seurat 
### Varying the k-param

```{r seurat k}
Seurat <- singleMethod %>% 
  filter(clustering_name == "Seurat") %>%
  mutate(level = str_extract(clustering_method, ",.*$") %>%
           str_remove(., "^,") %>%
           factor(., levels = c("30", "50", "100")),
         clustering_method = 
           str_extract(clustering_method, "^.*,") %>%
           str_remove(., "Seurat\\.") %>%
           str_remove(., ",$") %>%
           str_replace(., "_", "."))
ggplot(Seurat %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = clustering_method, shape = level)) +
  geom_point() +
  geom_path(aes(group = factor(clustering_method))) +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "# of clusters", y = "Replicability", col = "resolution",
       shape = "k param", title = "Seurat, varying the k parameter")
```

### Varying the resolution

```{r seurat resolution}
ggplot(Seurat %>% arrange(clustering_method),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  geom_path(aes(group = factor(level))) +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "# of clusters", y = "Replicability", col = "k param",
       title = "Seurat, varying the resolution parameter")
```

## SC3

```{r sc3}
SC3 <- singleMethod %>% 
         filter(clustering_name == "SC3") %>%
         mutate(level =
                  str_extract(clustering_method, "\\..*$") %>%
                  str_remove(., "^\\.") %>%
                  as.numeric())
ggplot(SC3 %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "# of clusters", y = "Replicability", col = "K",
       title = "SC3, varying the k parameter")
```

## Monocle

```{r Monocle}
Monocle <- singleMethod %>% 
  filter(clustering_name == "Monocle") %>%
  mutate(level = str_extract(clustering_method, "k_.*$") %>%
           str_remove(., "^k_") %>%
           as.numeric())
ggplot(Monocle %>% arrange(level),
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = level)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "# of clusters", y = "Replicability", col = "K",
       title = "Monocle, varying the k parameter")
```
  
## All at once

```{r all}
ggplot(singleMethod,
       aes(
         x = (replicable_clusters + non_replicable_clusters) / 2,
         y = fraction_replicable_cells,
         col = clustering_name)) +
  geom_point() +
  my_theme() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "# of clusters", y = "Replicability", col = "Clustering Method",
       title = "All three methods together")
```

# ARI Merging versus singleMerge
## Varying k for Seurat
```{r}
Seurat_k <- Seurat %>%
  mutate(level = as.numeric(level)) %>%
  filter((clustering_method == 1.6)# |
         # (clustering_method < 1.6 & level == 50)
        )
  
df <- bind_rows(SC3, Monocle, Seurat_k,
                ARIMerge %>% filter(clustering_name != "RSEC"))

ggplot(df %>%
         arrange(clustering_name, level),
       aes(x = (replicable_clusters + non_replicable_clusters) / 2,
               y = fraction_replicable_cells,
               col = clustering_name, linetype = merging_type)) +
  geom_path() +
  my_theme() +
  scale_color_brewer(type = "qual") +
  labs(x = "# of clusters", y = "Replicability", col = "Type of\nmerging") +
  theme(axis.title = element_text(size = 20),
        axis.text = element_text(size = 15),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 15))
```